package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Calendrier2 generated by hbm2java
 */
public class Calendrier2  implements java.io.Serializable {


     private String dater;
     private Set<Realisernormal> realisernormals = new HashSet<Realisernormal>(0);

    public Calendrier2() {
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.dater);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Calendrier2 other = (Calendrier2) obj;
        if (!Objects.equals(this.dater, other.dater)) {
            return false;
        }
        return true;
    }

	
    public Calendrier2(String dater) {
        this.dater = dater;
    }
    public Calendrier2(String dater, Set<Realisernormal> realisernormals) {
       this.dater = dater;
       this.realisernormals = realisernormals;
    }
   
    public String getDater() {
        return this.dater;
    }
    
    public void setDater(String dater) {
        this.dater = dater;
    }
    public Set<Realisernormal> getRealisernormals() {
        return this.realisernormals;
    }
    
    public void setRealisernormals(Set<Realisernormal> realisernormals) {
        this.realisernormals = realisernormals;
    }




}


