package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorieexo generated by hbm2java
 */
public class Categorieexo  implements java.io.Serializable {


     private int codecat;
     private String libellecat;
     private String descripcat;
     private Set<Exercice> exercices = new HashSet<Exercice>(0);

    public Categorieexo() {
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 73 * hash + this.codecat;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Categorieexo other = (Categorieexo) obj;
        if (this.codecat != other.codecat) {
            return false;
        }
        return true;
    }

	
    public Categorieexo(int codecat) {
        this.codecat = codecat;
    }
    public Categorieexo(int codecat, String libellecat, String descripcat, Set<Exercice> exercices) {
       this.codecat = codecat;
       this.libellecat = libellecat;
       this.descripcat = descripcat;
       this.exercices = exercices;
    }
   
    public int getCodecat() {
        return this.codecat;
    }
    
    public void setCodecat(int codecat) {
        this.codecat = codecat;
    }
    public String getLibellecat() {
        return this.libellecat;
    }
    
    public void setLibellecat(String libellecat) {
        this.libellecat = libellecat;
    }
    public String getDescripcat() {
        return this.descripcat;
    }
    
    public void setDescripcat(String descripcat) {
        this.descripcat = descripcat;
    }
    public Set<Exercice> getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set<Exercice> exercices) {
        this.exercices = exercices;
    }




}


