package metier;
// Generated 23 févr. 2018 05:43:28 by Hibernate Tools 4.3.1



/**
 * ChoisirId generated by hbm2java
 */
public class ChoisirId  implements java.io.Serializable {


     private int codep;
     private int codeprofil;

    public ChoisirId() {
    }

    public ChoisirId(int codep, int codeprofil) {
       this.codep = codep;
       this.codeprofil = codeprofil;
    }
   
    public int getCodep() {
        return this.codep;
    }
    
    public void setCodep(int codep) {
        this.codep = codep;
    }
    public int getCodeprofil() {
        return this.codeprofil;
    }
    
    public void setCodeprofil(int codeprofil) {
        this.codeprofil = codeprofil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChoisirId) ) return false;
		 ChoisirId castOther = ( ChoisirId ) other; 
         
		 return (this.getCodep()==castOther.getCodep())
 && (this.getCodeprofil()==castOther.getCodeprofil());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodep();
         result = 37 * result + this.getCodeprofil();
         return result;
   }   


}


