package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Choisir generated by hbm2java
 */
public class Choisir  implements java.io.Serializable {


     private ChoisirId id;
     private Profil profil;
     private Programme programme;
     private Integer dureep;

    public Choisir() {
    }

	
    public Choisir(ChoisirId id, Profil profil, Programme programme) {
        this.id = id;
        this.profil = profil;
        this.programme = programme;
    }
    public Choisir(ChoisirId id, Profil profil, Programme programme, Integer dureep) {
       this.id = id;
       this.profil = profil;
       this.programme = programme;
       this.dureep = dureep;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 43 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Choisir other = (Choisir) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
   
    public ChoisirId getId() {
        return this.id;
    }
    
    public void setId(ChoisirId id) {
        this.id = id;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Integer getDureep() {
        return this.dureep;
    }
    
    public void setDureep(Integer dureep) {
        this.dureep = dureep;
    }




}


