package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private int codec;
     private String nomc;
     private String prenomc;
     private String mailc;
     private Long telc;
     private String mdpc;
     private Set<Seance> seances = new HashSet<Seance>(0);
     private Set<Planifier> planifiers = new HashSet<Planifier>(0);

    public Coach() {
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 67 * hash + this.codec;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coach other = (Coach) obj;
        if (this.codec != other.codec) {
            return false;
        }
        return true;
    }

	
    public Coach(int codec) {
        this.codec = codec;
    }
    public Coach(int codec, String nomc, String prenomc, String mailc, Long telc, String mdpc, Set<Seance> seances, Set<Planifier> planifiers) {
       this.codec = codec;
       this.nomc = nomc;
       this.prenomc = prenomc;
       this.mailc = mailc;
       this.telc = telc;
       this.mdpc = mdpc;
       this.seances = seances;
       this.planifiers = planifiers;
    }
   
    public int getCodec() {
        return this.codec;
    }
    
    public void setCodec(int codec) {
        this.codec = codec;
    }
    public String getNomc() {
        return this.nomc;
    }
    
    public void setNomc(String nomc) {
        this.nomc = nomc;
    }
    public String getPrenomc() {
        return this.prenomc;
    }
    
    public void setPrenomc(String prenomc) {
        this.prenomc = prenomc;
    }
    public String getMailc() {
        return this.mailc;
    }
    
    public void setMailc(String mailc) {
        this.mailc = mailc;
    }
    public Long getTelc() {
        return this.telc;
    }
    
    public void setTelc(Long telc) {
        this.telc = telc;
    }
    public String getMdpc() {
        return this.mdpc;
    }
    
    public void setMdpc(String mdpc) {
        this.mdpc = mdpc;
    }
    public Set<Seance> getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set<Seance> seances) {
        this.seances = seances;
    }
    public Set<Planifier> getPlanifiers() {
        return this.planifiers;
    }
    
    public void setPlanifiers(Set<Planifier> planifiers) {
        this.planifiers = planifiers;
    }




}


