package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Corps generated by hbm2java
 */
public class Corps  implements java.io.Serializable {


     private int codecorps;
     private String partiecorps;
     private Set<Posseder> posseders = new HashSet<Posseder>(0);

    public Corps() {
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + this.codecorps;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Corps other = (Corps) obj;
        if (this.codecorps != other.codecorps) {
            return false;
        }
        return true;
    }

	
    public Corps(int codecorps) {
        this.codecorps = codecorps;
    }
    public Corps(int codecorps, String partiecorps, Set<Posseder> posseders) {
       this.codecorps = codecorps;
       this.partiecorps = partiecorps;
       this.posseders = posseders;
    }
   
    public int getCodecorps() {
        return this.codecorps;
    }
    
    public void setCodecorps(int codecorps) {
        this.codecorps = codecorps;
    }
    public String getPartiecorps() {
        return this.partiecorps;
    }
    
    public void setPartiecorps(String partiecorps) {
        this.partiecorps = partiecorps;
    }
    public Set<Posseder> getPosseders() {
        return this.posseders;
    }
    
    public void setPosseders(Set<Posseder> posseders) {
        this.posseders = posseders;
    }




}


