package metier;
// Generated 23 févr. 2018 05:43:28 by Hibernate Tools 4.3.1



/**
 * OrganiserId generated by hbm2java
 */
public class OrganiserId  implements java.io.Serializable {


     private int codee;
     private int codest;

    public OrganiserId() {
    }

    public OrganiserId(int codee, int codest) {
       this.codee = codee;
       this.codest = codest;
    }
   
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public int getCodest() {
        return this.codest;
    }
    
    public void setCodest(int codest) {
        this.codest = codest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrganiserId) ) return false;
		 OrganiserId castOther = ( OrganiserId ) other; 
         
		 return (this.getCodee()==castOther.getCodee())
 && (this.getCodest()==castOther.getCodest());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodee();
         result = 37 * result + this.getCodest();
         return result;
   }   


}


