package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Organiser generated by hbm2java
 */
public class Organiser  implements java.io.Serializable {


     private OrganiserId id;
     private Exercice exercice;
     private Seancetype seancetype;
     private Integer ordreo;
     private Integer seriest;

    public Organiser() {
    }

	
    public Organiser(OrganiserId id, Exercice exercice, Seancetype seancetype) {
        this.id = id;
        this.exercice = exercice;
        this.seancetype = seancetype;
    }
    public Organiser(OrganiserId id, Exercice exercice, Seancetype seancetype, Integer ordreo, Integer seriest) {
       this.id = id;
       this.exercice = exercice;
       this.seancetype = seancetype;
       this.ordreo = ordreo;
       this.seriest = seriest;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Organiser other = (Organiser) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
   
    public OrganiserId getId() {
        return this.id;
    }
    
    public void setId(OrganiserId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seancetype getSeancetype() {
        return this.seancetype;
    }
    
    public void setSeancetype(Seancetype seancetype) {
        this.seancetype = seancetype;
    }
    public Integer getOrdreo() {
        return this.ordreo;
    }
    
    public void setOrdreo(Integer ordreo) {
        this.ordreo = ordreo;
    }
    public Integer getSeriest() {
        return this.seriest;
    }
    
    public void setSeriest(Integer seriest) {
        this.seriest = seriest;
    }




}


