package metier;
// Generated 23 févr. 2018 05:43:28 by Hibernate Tools 4.3.1



/**
 * PlanifierId generated by hbm2java
 */
public class PlanifierId  implements java.io.Serializable {


     private int codee;
     private int codes;
     private int codec;

    public PlanifierId() {
    }

    public PlanifierId(int codee, int codes, int codec) {
       this.codee = codee;
       this.codes = codes;
       this.codec = codec;
    }
   
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public int getCodes() {
        return this.codes;
    }
    
    public void setCodes(int codes) {
        this.codes = codes;
    }
    public int getCodec() {
        return this.codec;
    }
    
    public void setCodec(int codec) {
        this.codec = codec;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanifierId) ) return false;
		 PlanifierId castOther = ( PlanifierId ) other; 
         
		 return (this.getCodee()==castOther.getCodee())
 && (this.getCodes()==castOther.getCodes())
 && (this.getCodec()==castOther.getCodec());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodee();
         result = 37 * result + this.getCodes();
         result = 37 * result + this.getCodec();
         return result;
   }   


}


