package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Planifier generated by hbm2java
 */
public class Planifier  implements java.io.Serializable {


     private PlanifierId id;
     private Coach coach;
     private Exercice exercice;
     private Seance seance;
     private Integer ordrep;
     private Integer nbrepe;
     private Integer tempse;
     private Integer tempsrepose;
     private Integer seriep;

    public Planifier() {
    }

    public Integer getSeriep() {
        return seriep;
    }

    public void setSeriep(Integer seriep) {
        this.seriep = seriep;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Planifier other = (Planifier) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

	
    public Planifier(PlanifierId id, Coach coach, Exercice exercice, Seance seance) {
        this.id = id;
        this.coach = coach;
        this.exercice = exercice;
        this.seance = seance;
    }
    public Planifier(PlanifierId id, Coach coach, Exercice exercice, Seance seance, Integer ordrep, Integer nbrepe, Integer tempse, Integer tempsrepose) {
       this.id = id;
       this.coach = coach;
       this.exercice = exercice;
       this.seance = seance;
       this.ordrep = ordrep;
       this.nbrepe = nbrepe;
       this.tempse = tempse;
       this.tempsrepose = tempsrepose;
    }
   
    public PlanifierId getId() {
        return this.id;
    }
    
    public void setId(PlanifierId id) {
        this.id = id;
    }
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getOrdrep() {
        return this.ordrep;
    }
    
    public void setOrdrep(Integer ordrep) {
        this.ordrep = ordrep;
    }
    public Integer getNbrepe() {
        return this.nbrepe;
    }
    
    public void setNbrepe(Integer nbrepe) {
        this.nbrepe = nbrepe;
    }
    public Integer getTempse() {
        return this.tempse;
    }
    
    public void setTempse(Integer tempse) {
        this.tempse = tempse;
    }
    public Integer getTempsrepose() {
        return this.tempsrepose;
    }
    
    public void setTempsrepose(Integer tempsrepose) {
        this.tempsrepose = tempsrepose;
    }
    



}


