package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Posseder generated by hbm2java
 */
public class Posseder  implements java.io.Serializable {


     private PossederId id;
     private Calendrier1 calendrier1;
     private Corps corps;
     private Utilisateur utilisateur;
     private Double mesure;

    public Posseder() {
    }

	
    public Posseder(PossederId id, Calendrier1 calendrier1, Corps corps, Utilisateur utilisateur) {
        this.id = id;
        this.calendrier1 = calendrier1;
        this.corps = corps;
        this.utilisateur = utilisateur;
    }
    public Posseder(PossederId id, Calendrier1 calendrier1, Corps corps, Utilisateur utilisateur, Double mesure) {
       this.id = id;
       this.calendrier1 = calendrier1;
       this.corps = corps;
       this.utilisateur = utilisateur;
       this.mesure = mesure;
    }
   
    public PossederId getId() {
        return this.id;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Posseder other = (Posseder) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
    
    public void setId(PossederId id) {
        this.id = id;
    }
    public Calendrier1 getCalendrier1() {
        return this.calendrier1;
    }
    
    public void setCalendrier1(Calendrier1 calendrier1) {
        this.calendrier1 = calendrier1;
    }
    public Corps getCorps() {
        return this.corps;
    }
    
    public void setCorps(Corps corps) {
        this.corps = corps;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Double getMesure() {
        return this.mesure;
    }
    
    public void setMesure(Double mesure) {
        this.mesure = mesure;
    }




}


