package metier;
// Generated 23 févr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PossederId generated by hbm2java
 */
public class PossederId  implements java.io.Serializable {


     private int codeu;
     private int codecorps;
     private Date dateh;

    public PossederId() {
    }

    public PossederId(int codeu, int codecorps, Date dateh) {
       this.codeu = codeu;
       this.codecorps = codecorps;
       this.dateh = dateh;
    }
   
    public int getCodeu() {
        return this.codeu;
    }
    
    public void setCodeu(int codeu) {
        this.codeu = codeu;
    }
    public int getCodecorps() {
        return this.codecorps;
    }
    
    public void setCodecorps(int codecorps) {
        this.codecorps = codecorps;
    }
    public Date getDateh() {
        return this.dateh;
    }
    
    public void setDateh(Date dateh) {
        this.dateh = dateh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PossederId) ) return false;
		 PossederId castOther = ( PossederId ) other; 
         
		 return (this.getCodeu()==castOther.getCodeu())
 && (this.getCodecorps()==castOther.getCodecorps())
 && ( (this.getDateh()==castOther.getDateh()) || ( this.getDateh()!=null && castOther.getDateh()!=null && this.getDateh().equals(castOther.getDateh()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeu();
         result = 37 * result + this.getCodecorps();
         result = 37 * result + ( getDateh() == null ? 0 : this.getDateh().hashCode() );
         return result;
   }   


}


