package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private int codeprofil;
     private String libelleprofil;
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
     private Set<Choisir> choisirs = new HashSet<Choisir>(0);

    public Profil() {
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + this.codeprofil;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Profil other = (Profil) obj;
        if (this.codeprofil != other.codeprofil) {
            return false;
        }
        return true;
    }

	
    public Profil(int codeprofil) {
        this.codeprofil = codeprofil;
    }
    public Profil(int codeprofil, String libelleprofil, Set<Utilisateur> utilisateurs, Set<Choisir> choisirs) {
       this.codeprofil = codeprofil;
       this.libelleprofil = libelleprofil;
       this.utilisateurs = utilisateurs;
       this.choisirs = choisirs;
    }
   
    public int getCodeprofil() {
        return this.codeprofil;
    }
    
    public void setCodeprofil(int codeprofil) {
        this.codeprofil = codeprofil;
    }
    public String getLibelleprofil() {
        return this.libelleprofil;
    }
    
    public void setLibelleprofil(String libelleprofil) {
        this.libelleprofil = libelleprofil;
    }
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }
    public Set<Choisir> getChoisirs() {
        return this.choisirs;
    }
    
    public void setChoisirs(Set<Choisir> choisirs) {
        this.choisirs = choisirs;
    }




}


