package metier;
// Generated 23 févr. 2018 05:43:28 by Hibernate Tools 4.3.1



/**
 * RealisernormalId generated by hbm2java
 */
public class RealisernormalId  implements java.io.Serializable {


     private int codes;
     private int codee;
     private String dater;

    public RealisernormalId() {
    }

    public RealisernormalId(int codes, int codee, String dater) {
       this.codes = codes;
       this.codee = codee;
       this.dater = dater;
    }
   
    public int getCodes() {
        return this.codes;
    }
    
    public void setCodes(int codes) {
        this.codes = codes;
    }
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public String getDater() {
        return this.dater;
    }
    
    public void setDater(String dater) {
        this.dater = dater;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RealisernormalId) ) return false;
		 RealisernormalId castOther = ( RealisernormalId ) other; 
         
		 return (this.getCodes()==castOther.getCodes())
 && (this.getCodee()==castOther.getCodee())
 && ( (this.getDater()==castOther.getDater()) || ( this.getDater()!=null && castOther.getDater()!=null && this.getDater().equals(castOther.getDater()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodes();
         result = 37 * result + this.getCodee();
         result = 37 * result + ( getDater() == null ? 0 : this.getDater().hashCode() );
         return result;
   }   


}


