package metier;
// Generated 23 févr. 2018 05:43:28 by Hibernate Tools 4.3.1



/**
 * RealiserbilanId generated by hbm2java
 */
public class RealiserbilanId  implements java.io.Serializable {


     private int codes;
     private int codee;

    public RealiserbilanId() {
    }

    public RealiserbilanId(int codes, int codee) {
       this.codes = codes;
       this.codee = codee;
    }
   
    public int getCodes() {
        return this.codes;
    }
    
    public void setCodes(int codes) {
        this.codes = codes;
    }
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RealiserbilanId) ) return false;
		 RealiserbilanId castOther = ( RealiserbilanId ) other; 
         
		 return (this.getCodes()==castOther.getCodes())
 && (this.getCodee()==castOther.getCodee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodes();
         result = 37 * result + this.getCodee();
         return result;
   }   


}


