package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Realiserbilan generated by hbm2java
 */
public class Realiserbilan  implements java.io.Serializable {


     private RealiserbilanId id;
     private Exercice exercice;
     private Seance seance;
     private Integer maxrep;
     private Integer maxtemps;

    public Realiserbilan() {
    }

	
    public Realiserbilan(RealiserbilanId id, Exercice exercice, Seance seance) {
        this.id = id;
        this.exercice = exercice;
        this.seance = seance;
    }
    public Realiserbilan(RealiserbilanId id, Exercice exercice, Seance seance, Integer maxrep, Integer maxtemps) {
       this.id = id;
       this.exercice = exercice;
       this.seance = seance;
       this.maxrep = maxrep;
       this.maxtemps = maxtemps;
    }
   
    public RealiserbilanId getId() {
        return this.id;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Realiserbilan other = (Realiserbilan) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
    
    public void setId(RealiserbilanId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getMaxrep() {
        return this.maxrep;
    }
    
    public void setMaxrep(Integer maxrep) {
        this.maxrep = maxrep;
    }
    public Integer getMaxtemps() {
        return this.maxtemps;
    }
    
    public void setMaxtemps(Integer maxtemps) {
        this.maxtemps = maxtemps;
    }




}


