package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private int codes;
     private Coach coach;
     private Programme programme;
     private Seancetype seancetype;
     private Utilisateur utilisateur;
     private String libelles;
     private String descrips;
     private String commentairecoa;
     private Integer nbreps;
     private Integer numsemaine;
     private String etatlucoa;
     private Set<Realiserbilan> realiserbilans = new HashSet<Realiserbilan>(0);
     private Set<Realisernormal> realisernormals = new HashSet<Realisernormal>(0);
     private Set<Planifier> planifiers = new HashSet<Planifier>(0);

    public Seance() {
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 43 * hash + this.codes;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seance other = (Seance) obj;
        if (this.codes != other.codes) {
            return false;
        }
        return true;
    }

	
    public Seance(int codes, Programme programme, Utilisateur utilisateur) {
        this.codes = codes;
        this.programme = programme;
        this.utilisateur = utilisateur;
    }
    public Seance(int codes, Coach coach, Programme programme, Seancetype seancetype, Utilisateur utilisateur, String libelles, String descrips, String commentairecoa, Integer nbreps, Integer numsemaine, String etatlucoa, Set<Realiserbilan> realiserbilans, Set<Realisernormal> realisernormals, Set<Planifier> planifiers) {
       this.codes = codes;
       this.coach = coach;
       this.programme = programme;
       this.seancetype = seancetype;
       this.utilisateur = utilisateur;
       this.libelles = libelles;
       this.descrips = descrips;
       this.commentairecoa = commentairecoa;
       this.nbreps = nbreps;
       this.numsemaine = numsemaine;
       this.etatlucoa = etatlucoa;
       this.realiserbilans = realiserbilans;
       this.realisernormals = realisernormals;
       this.planifiers = planifiers;
    }
   
    public int getCodes() {
        return this.codes;
    }
    
    public void setCodes(int codes) {
        this.codes = codes;
    }
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Seancetype getSeancetype() {
        return this.seancetype;
    }
    
    public void setSeancetype(Seancetype seancetype) {
        this.seancetype = seancetype;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getLibelles() {
        return this.libelles;
    }
    
    public void setLibelles(String libelles) {
        this.libelles = libelles;
    }
    public String getDescrips() {
        return this.descrips;
    }
    
    public void setDescrips(String descrips) {
        this.descrips = descrips;
    }
    public String getCommentairecoa() {
        return this.commentairecoa;
    }
    
    public void setCommentairecoa(String commentairecoa) {
        this.commentairecoa = commentairecoa;
    }
    public Integer getNbreps() {
        return this.nbreps;
    }
    
    public void setNbreps(Integer nbreps) {
        this.nbreps = nbreps;
    }
    public Integer getNumsemaine() {
        return this.numsemaine;
    }
    
    public void setNumsemaine(Integer numsemaine) {
        this.numsemaine = numsemaine;
    }
    public String getEtatlucoa() {
        return this.etatlucoa;
    }
    
    public void setEtatlucoa(String etatlucoa) {
        this.etatlucoa = etatlucoa;
    }
    public Set<Realiserbilan> getRealiserbilans() {
        return this.realiserbilans;
    }
    
    public void setRealiserbilans(Set<Realiserbilan> realiserbilans) {
        this.realiserbilans = realiserbilans;
    }
    public Set<Realisernormal> getRealisernormals() {
        return this.realisernormals;
    }
    
    public void setRealisernormals(Set<Realisernormal> realisernormals) {
        this.realisernormals = realisernormals;
    }
    public Set<Planifier> getPlanifiers() {
        return this.planifiers;
    }
    
    public void setPlanifiers(Set<Planifier> planifiers) {
        this.planifiers = planifiers;
    }




}


