package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seancetype generated by hbm2java
 */
public class Seancetype  implements java.io.Serializable {


     private int codest;
     private String libellest;
     private String descripst;
     private Set<Organiser> organisers = new HashSet<Organiser>(0);
     private Set<Programme> programmes = new HashSet<Programme>(0);
     private Set<Seance> seances = new HashSet<Seance>(0);

    public Seancetype() {
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.codest;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seancetype other = (Seancetype) obj;
        if (this.codest != other.codest) {
            return false;
        }
        return true;
    }

	
    public Seancetype(int codest) {
        this.codest = codest;
    }
    public Seancetype(int codest, String libellest, String descripst, Set<Organiser> organisers, Set<Programme> programmes, Set<Seance> seances) {
       this.codest = codest;
       this.libellest = libellest;
       this.descripst = descripst;
       this.organisers = organisers;
       this.programmes = programmes;
       this.seances = seances;
    }
   
    public int getCodest() {
        return this.codest;
    }
    
    public void setCodest(int codest) {
        this.codest = codest;
    }
    public String getLibellest() {
        return this.libellest;
    }
    
    public void setLibellest(String libellest) {
        this.libellest = libellest;
    }
    public String getDescripst() {
        return this.descripst;
    }
    
    public void setDescripst(String descripst) {
        this.descripst = descripst;
    }
    public Set<Organiser> getOrganisers() {
        return this.organisers;
    }
    
    public void setOrganisers(Set<Organiser> organisers) {
        this.organisers = organisers;
    }
    public Set<Programme> getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set<Programme> programmes) {
        this.programmes = programmes;
    }
    public Set<Seance> getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set<Seance> seances) {
        this.seances = seances;
    }




}


