package metier;
// Generated 23 f�vr. 2018 05:43:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private int codeu;
     private String nomu;
     private String prenomu;
     private String mailu;
     private String genreu;
     private Date datenaissance;
     private String mdpu;
     private String statutu;
     private String adresseu;
     private String profilu;
     private Double poids;
     private Double taille;
     private Long telu;
     private Set<Profil> profils = new HashSet<Profil>(0);
     private Set<Posseder> posseders = new HashSet<Posseder>(0);
     private Set<Seance> seances = new HashSet<Seance>(0);

    public Utilisateur() {
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + this.codeu;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Utilisateur other = (Utilisateur) obj;
        if (this.codeu != other.codeu) {
            return false;
        }
        return true;
    }

	
    public Utilisateur(int codeu) {
        this.codeu = codeu;
    }
    public Utilisateur(int codeu, String nomu, String prenomu, String mailu, String genreu, Date datenaissance, String mdpu, String statutu, String adresseu, String profilu, Double poids, Double taille, Long telu, Set<Profil> profils, Set<Posseder> posseders, Set<Seance> seances) {
       this.codeu = codeu;
       this.nomu = nomu;
       this.prenomu = prenomu;
       this.mailu = mailu;
       this.genreu = genreu;
       this.datenaissance = datenaissance;
       this.mdpu = mdpu;
       this.statutu = statutu;
       this.adresseu = adresseu;
       this.profilu = profilu;
       this.poids = poids;
       this.taille = taille;
       this.telu = telu;
       this.profils = profils;
       this.posseders = posseders;
       this.seances = seances;
    }
   
    public int getCodeu() {
        return this.codeu;
    }
    
    public void setCodeu(int codeu) {
        this.codeu = codeu;
    }
    public String getNomu() {
        return this.nomu;
    }
    
    public void setNomu(String nomu) {
        this.nomu = nomu;
    }
    public String getPrenomu() {
        return this.prenomu;
    }
    
    public void setPrenomu(String prenomu) {
        this.prenomu = prenomu;
    }
    public String getMailu() {
        return this.mailu;
    }
    
    public void setMailu(String mailu) {
        this.mailu = mailu;
    }
    public String getGenreu() {
        return this.genreu;
    }
    
    public void setGenreu(String genreu) {
        this.genreu = genreu;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getMdpu() {
        return this.mdpu;
    }
    
    public void setMdpu(String mdpu) {
        this.mdpu = mdpu;
    }
    public String getStatutu() {
        return this.statutu;
    }
    
    public void setStatutu(String statutu) {
        this.statutu = statutu;
    }
    public String getAdresseu() {
        return this.adresseu;
    }
    
    public void setAdresseu(String adresseu) {
        this.adresseu = adresseu;
    }
    public String getProfilu() {
        return this.profilu;
    }
    
    public void setProfilu(String profilu) {
        this.profilu = profilu;
    }
    public Double getPoids() {
        return this.poids;
    }
    
    public void setPoids(Double poids) {
        this.poids = poids;
    }
    public Double getTaille() {
        return this.taille;
    }
    
    public void setTaille(Double taille) {
        this.taille = taille;
    }
    public Long getTelu() {
        return this.telu;
    }
    
    public void setTelu(Long telu) {
        this.telu = telu;
    }
    public Set<Profil> getProfils() {
        return this.profils;
    }
    
    public void setProfils(Set<Profil> profils) {
        this.profils = profils;
    }
    public Set<Posseder> getPosseders() {
        return this.posseders;
    }
    
    public void setPosseders(Set<Posseder> posseders) {
        this.posseders = posseders;
    }
    public Set<Seance> getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set<Seance> seances) {
        this.seances = seances;
    }




}


